# Generated by Django 4.1.4 on 2023-06-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
